let name= "harry";
console.log(name.length);
let boy1="pramod";
let boy2="nikhil";
let sentence= `${boy2} is  friend of ${boy1}`;
console.log(sentence);
var a="99";
var num=parseInt(a);
console.log(num);
let b="100";
let bun=Number.isInteger(b);
console.log(bun);
let c=5.6789;
let can=Number.toFixed(3);
console.log(can);